title: Marie's Snippets
description: An unstructured blog containing topics I am learning about at the moment.
github_username: mariestolk

timezone: Europe/Amsterdam

email:
twitter_username:

use_math: true
future: false

google_analytics:

theme: minima

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown

kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge